nginx:
    image: linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Hungary
    volumes:
      - /home/user/appdata/nginx:/config
    ports:
      - 81:80
    restart: unless-stopped